version: "3"
services:
  recommendation-api:
    build: .
    container_name: recommendation-api
    ports:
      - 5000:5000
    networks:
      - mongo
    restart: unless-stopped

networks:
  pizzabot:
    external:
      name: mongo
