version: "3"
services:
  recommendation-api:
    build: .
    container_name: recommendation-api
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - DATABASE_NAME=${DATABASE_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
    ports:
      - 5000:5000
    networks:
      - pizzabot
    restart: unless-stopped

networks:
  pizzabot:
    external:
      name: docker_pizzabot
